Feature api endpoints
Graciano1997/technology_blog_app pull request #18
Opened 2023-11-21 17:33 UTC by Graciano1997

In this milestone we did the bellow project's requirements:

- Create an API endpoint to list all posts for a user.
- Create an API endpoint to list all comments for a user's post.
- Create an API endpoint to add a comment to a post. Remember that the owner of the comment is the user that makes it; it should not be set by passing a parameter.
- Your API endpoints should receive JSON and respond JSON as well.
Update readme
fix linter issues

2023-11-22 10:25 UTC, danmainah requested changes
Hi @Graciano1997 and @pushkar1995 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ Added API endpoints to list posts, comments and add comments.
✔️ Added route to access the endpoints.

# Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-11-22 10:25 UTC, danmainah commented on app/controllers/API/V1/comments_controller.rb
>      @comment = @post.comments.new(text: comment_params[:text], user_id: current_user.id)
- [ ] @Team Great work adding controllers for your API, when I  run the API in Postman I get the error below
![image](https://github.com/Graciano1997/technology_blog_app/assets/61408860/2a69be88-b686-4496-a910-cf816817a3d5)
![image](https://github.com/Graciano1997/technology_blog_app/assets/61408860/e0e5a9c3-512f-4493-954b-016a5689a257)

2023-11-23 02:18 UTC, Graciano1997 commented
Hello Code reviewers 

![image](https://github.com/Graciano1997/technology_blog_app/assets/88609043/388b75be-2ecb-4c46-8cf4-4be1efc583ca)


![image](https://github.com/Graciano1997/technology_blog_app/assets/88609043/5c3df964-5539-4286-b2e9-e4414237f9d2)


![image](https://github.com/Graciano1997/technology_blog_app/assets/88609043/b9752166-2fee-4a22-a2ae-14297ee1a552)

![image](https://github.com/Graciano1997/technology_blog_app/assets/88609043/33cb3025-886d-4238-b3d8-756553e9c568)
☝️ ☝️  shows the user token message

2023-11-23 03:37 UTC, Davidosky007 requested changes
Hi @Graciano1997 @sheezu900 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
* Well-written PR 👍 
* No linter errors 👍 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @davidosky007 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-23 03:37 UTC, Davidosky007 commented on app/controllers/API/V1/posts_controller.rb
> +    @posts = User.find(params[:user_id]).posts.order('created_at')
* Even after adding a bearer token I still get the error reported by the previous CR kindly look into it 
![image](https://github.com/Graciano1997/technology_blog_app/assets/52497246/4c1197f7-0856-41e2-96fd-9744b9d8de76)

2023-11-23 11:59 UTC, V-Blaze approved these changes
Hi @kifle23 , 

# Approved 🟢 🟢 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![giphy](https://user-images.githubusercontent.com/107632780/229644741-7dea3027-bf3f-4416-855b-46095e3bf6d5.gif)

## Highlights
- All required Endpoints created✔✔
- Followed a common practice to add  `api/v1` :heavy_check_mark: 
- All controller methods works as expected :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-23 21:59 UTC, merged